### ISSUE TITLE
Version 1.07 und 1.06 laufen nicht 1.05 ist stabil

### ISSUE THREAD

**Issue by totti1171** [nobl/ioBroker.senec#3]
**Describe the bug**  
seltsamerweise funktioniert (bei mir) alles bis zur Version 1.05 
in den folgenden Versionen wird der Adapter rot. 

(Einmal bekommt der Adapter Daten vom Akku, dann Fehlermeldungen)

**To Reproduce**  
```
2020-05-01 00:02:35.826  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: STATISTIC.UPLOAD_B64
2020-05-01 00:02:35.844  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: FEATURES.ISLAND_PRO
2020-05-01 00:02:35.847  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: SYS_UPDATE.MISC
2020-05-01 00:02:35.851  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: WIZARD.BOOT
2020-05-01 00:02:35.861  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: WIZARD.INSULATION_RESISTANCE
2020-05-01 00:02:35.868  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: WIZARD.PV_CONFIG
2020-05-01 00:02:35.876  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: WIZARD.SG_READY_ENABLED
2020-05-01 00:02:35.877  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: WIZARD.SG_READY_EN_MODE1
2020-05-01 00:02:35.877  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: WIZARD.SG_READY_POWER_COMM
2020-05-01 00:02:35.878  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: WIZARD.SG_READY_POWER_PROP
2020-05-01 00:02:35.879  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: WIZARD.SG_READY_TIME
2020-05-01 00:02:35.880  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.ALARM_STATUS
2020-05-01 00:02:35.881  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.ALLOWRECOVER
2020-05-01 00:02:35.882  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.BATTERY_STATUS
2020-05-01 00:02:35.885  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.COMMERRCOUNT
2020-05-01 00:02:35.887  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.DERATING
2020-05-01 00:02:35.890  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.FAULTLINECOUNT
2020-05-01 00:02:35.893  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.MAX_TEMP
2020-05-01 00:02:35.895  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.MIN_TEMP
2020-05-01 00:02:35.896  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.NR_ACTIVE
2020-05-01 00:02:35.897  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.NR_CHARGE
2020-05-01 00:02:35.898  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.NR_DISCHARGE
2020-05-01 00:02:35.899  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.NR_INSTALLED
2020-05-01 00:02:35.899  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.PROTOCOL
2020-05-01 00:02:35.903  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.START_RL_TST
2020-05-01 00:02:35.904  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.SYSTEM_SOC
2020-05-01 00:02:35.906  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.TOTAL_CURRENT
2020-05-01 00:02:35.907  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BMS.TOTAL_VOLTAGE
2020-05-01 00:02:35.910  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1.NSP2_FW
2020-05-01 00:02:35.911  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1.REQ_HV_UPD
2020-05-01 00:02:35.912  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1.REQ_LV_UPD
2020-05-01 00:02:35.913  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1.SPARE_CAPACITY
2020-05-01 00:02:35.914  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ1.ERROR
2020-05-01 00:02:35.915  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ1.P
2020-05-01 00:02:35.916  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ1.Q
2020-05-01 00:02:35.917  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ1.S
2020-05-01 00:02:35.917  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ1.STATE
2020-05-01 00:02:35.918  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ1.SW_VERSION2
2020-05-01 00:02:35.919  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ1.SW_VERSION3
2020-05-01 00:02:35.922  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ2.ERROR
2020-05-01 00:02:35.923  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ2.P
2020-05-01 00:02:35.924  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ2.Q
2020-05-01 00:02:35.924  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ2.S
2020-05-01 00:02:35.925  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ2.STATE
2020-05-01 00:02:35.926  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ2.SW_VERSION2
2020-05-01 00:02:35.927  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ2.SW_VERSION3
2020-05-01 00:02:35.929  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ3.ERROR
2020-05-01 00:02:35.930  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ3.P
2020-05-01 00:02:35.931  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ3.Q
2020-05-01 00:02:35.931  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ3.S
2020-05-01 00:02:35.932  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ3.STATE
2020-05-01 00:02:35.933  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ3.SW_VERSION2
2020-05-01 00:02:35.934  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: BAT1OBJ3.SW_VERSION3
2020-05-01 00:02:35.970  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: PV1.ERROR_STATE_INT
2020-05-01 00:02:35.972  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: PV1.MPP_INT
2020-05-01 00:02:35.973  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: PV1.STATE_INT
2020-05-01 00:02:35.974  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: PV1.VERSION1_INT
2020-05-01 00:02:35.975  - [33mwarn[39m: senec.0 (30913) (lowPrio) State attribute definition missing for: PV1.VERSION2_INT
2020-05-01 00:02:35.987  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.988  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.989  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.989  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.989  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.990  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.990  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.991  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.991  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.992  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.992  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.992  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.993  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.993  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.994  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.994  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.994  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.995  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.995  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.996  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.996  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.996  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.997  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.997  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.998  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.998  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.998  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:35.999  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:35.999  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:36.000  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:36.000  - [31merror[39m: senec.0 (30913) uncaught exception: Cannot read property 'val' of null
2020-05-01 00:02:36.001  - [31merror[39m: senec.0 (30913) TypeError: Cannot read property 'val' of null
    at Senec.doState (/opt/iobroker/node_modules/iobroker.senec/main.js:306:60)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-05-01 00:02:36.146  - [34mdebug[39m: senec.0 (30913) Update: ENERGY.STAT_HOURS_OF_OPERATION: 30751 -> 30752
2020-05-01 00:02:36.652  - [32minfo[39m: host.buanet-iobroker2 instance system.adapter.senec.0 terminated with code 0 (NO_ERROR)
2020-05-01 00:02:36.652  - [32minfo[39m: host.buanet-iobroker2 Restart adapter system.adapter.senec.0 because enabled
```

**Comment by nobl** [comment]
Ok - da hat SENEC einiges neu hinzugefügt - das ist kein Problem.
Und ansonsten mal wieder was entfernt, wies aussieht. Ich kümmere mich drum.

**Comment by nobl** [comment]
Das Problem sollte jetzt behoben sein.
Die "missing state_attribute" Meldungen kommen jetzt auch nur noch im debug-mode. Diese bedeuten, dass das Attribut dem Adapter bisher nicht bekannt ist und mit Default-Einstellungen verarbeitet wird.

Sollte es also einmal neue Attribute geben, die eine Einheit oder speziellere Beschreibung erhalten sollten, deren Wert z.B. mit 0.1 multipliziert werden müsste (manchmal liefert Senec die Werte etwas seltsam), die statt 0/1 eher false/true anzeigen sollten, etc. pp.:
Dann bitte einfach Ticket und sie können hinzugefügt werden.

Bitte kurze Rückmeldung. Danke!

**Comment by totti1171** [comment]
Ja - es sieht gut aus! ;-) Danke !

`



senec.0 | 2020-05-01 13:28:18.308 | debug | (21965) Body: {"ENERGY":{"STAT_STATE":"u8_0E","STAT_STATE_DECODE":"u8_0E","GUI_BAT_DATA_POWER":"fl_44DA44CD","GUI_INVERTER_POWER":"fl_4511E599","GUI_HOUSE_POW":"fl_43BA55BC","GUI_GRID_POW":"fl_C35787A
senec.0 | 2020-05-01 13:28:18.307 | debug | (21965) Response: {"statusCode":200,"body":"{\"ENERGY\":{\"STAT_STATE\":\"u8_0E\",\"STAT_STATE_DECODE\":\"u8_0E\",\"GUI_BAT_DATA_POWER\":\"fl_44DA44CD\",\"GUI_INVERTER_POWER\":\"fl_4511E599\",\"GUI_HO
senec.0 | 2020-05-01 13:28:18.307 | debug | (21965) Status: 200
host.buanet-iobroker2 | 2020-05-01 13:28:05.030 | info

`

**Comment by nobl** [comment]
Perfekt!
Danke für die schnelle Rückmeldung.

Und natürlich immer gerne auch Infos, falls ein State angepasst werden sollte bzgl. Beschreibung, Einheit, ...

**Comment by totti1171** [comment]
Naja,

Ein Traum wäre ja noch die RedMatic (node red) Integration…

Also die Möglichkeit SENEC ohne Umwege dort direkt auszuwerten.

Gruss

Torsten

**Comment by nobl** [comment]
Das ist glücklicherweise die Baustelle für jemand anderen :)

**Comment by totti1171** [comment]
Schaaaade… Hätte ja sein können… ;-)
